databases:
  - name: nirmaan-db
    databaseName: nirmaan
    user: nirmaan_user
    plan: free

services:
  - type: web
    name: nirmaan-api
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: nirmaan-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nirmaan-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: nirmaan-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: nirmaan-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nirmaan-db
          property: password
      - key: JWT_SECRET
        generateValue: true
